# Generated by Django 4.2.6 on 2024-03-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0011_auto_20200709_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='categorys',
        ),
    ]
