# Generated by Django 4.2.11 on 2024-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0013_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_man',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
